AEB_thres: 0.2
KD: 0.14
KD_for_speed: 0.2
KI: 0.0
KI_for_speed: 0.5
KP: 1.6
KP_for_speed: 1.45
a_x_max: 5.0
a_y_max: 5.0
acc_scaler_for_steer: 0.9
b_ax_max_machines: 3.0
blind_trailing_speed: 1.5
curvature_factor: 0.145
dec_scaler_for_steer: 0.9
downscale_factor: 0.5
dyn_model_exp: 1.2
end_scale_speed: 10.0
future_constant: 0.08
heading_error_thres: 10.0
lat_err_coeff: 1.0
m_l1: 0.47
prioritize_dyn: false
q_l1: -0.2
speed_diff_thres: 0.1
speed_factor_for_curvature: 1.0
speed_factor_for_lat_err: 1.0
speed_lookahead: 0.25
speed_lookahead_for_steer: 0.0
start_curvature_factor: 1.5
start_scale_speed: 6.5
start_speed: 10.0
steer_gain_for_speed: 1.0
t_clip_max: 8.0
t_clip_min: 0.7
trailing_d_gain: 1.0
trailing_gap: 1.55
trailing_i_gain: 0.0
trailing_p_gain: 1.35
trailing_vel_gain: 0.25
v_max: 8.0
velocity_step: 0.5
