free_scaling_reference_distance_m: 1
hyst_timer_sec: 6.0
is_closed: false
killing_timer_sec: 10.0
lateral_width_m: 0.2
latest_threshold: 0.1
max_horizon: 10.0
min_horizon: 0.0
on_spline_front_horizon_thres_m: 2.0
on_spline_min_dist_thres_m: 0.5
