min_horizon: 0.0
max_horizon: 10.0
lateral_width_m: 0.1
free_scaling_reference_distance_m: 2.0
latest_threshold: 0.1
hyst_timer_sec: 4.0
killing_timer_sec: 10.0
on_spline_front_horizon_thres_m: 0.5
on_spline_min_dist_thres_m: 0.5
is_closed: False
