P_d: 0.02
P_vd: 0.2
P_vs: 0.2
aggro_multi: 2.0
boundaries_inflation: 0.1
debug_mode: false
dist_deletion: 7.0
dist_infront: 8.0
filter_kernel_size: 7
lambda_deg: 10.0
max_dist: 0.5
max_size_m: 0.6
max_std: 0.2
max_viewing_distance: 9.0
measurment_var_d: 0.002
measurment_var_s: 0.002
measurment_var_vd: 0.2
measurment_var_vs: 0.2
min_2_points_dist: 0.01
min_nb_meas: 5
min_size_m: 0.3
min_size_n: 4
min_std: 0.16
new_cluster_threshold_m: 0.4
noMemoryMode: true
process_var_vd: 8
process_var_vs: 2
publish_static: true
rate_detect: 40
rate_tracking: 40
ratio_to_glob_path: 0.6
sigma: 0.03
ttl_dynamic: 40
ttl_static: 3
var_pub: 1
vs_reset: 0.1
