l1_param:
  t_clip_min:
    lower_bound: 0.5
    upper_bound: 0.9
  m_l1:
    lower_bound: 0.3
    upper_bound: 0.6
  q_l1:
    lower_bound: -0.2
    upper_bound: 0.1

Sector0:
  lower_bound: 0.7
  upper_bound: 0.85
Sector1:
  lower_bound: 0.85
  upper_bound: 0.95
Sector2:
  lower_bound: 0.7
  upper_bound: 0.85
Sector3:
  lower_bound: 0.7
  upper_bound: 0.85
Sector4:
  lower_bound: 0.7
  upper_bound: 0.85
Sector5:
  lower_bound: 0.85
  upper_bound: 0.95
Sector6:
  lower_bound: 0.7
  upper_bound: 0.85
Sector7:
  lower_bound: 0.7
  upper_bound: 0.85

