KD: 0.05
KD_for_speed: 0.2
KI: 0.0
KI_for_speed: 0.5
KP: 0.5
KP_for_speed: 1.5
acc_scaler_for_steer: 1.0
blind_trailing_speed: 1.5
curvature_factor: 2.5
dec_scaler_for_steer: 1.0
downscale_factor: 0.5
end_scale_speed: 8.0
future_constant: 0.0
heading_error_thres: 10.0
lat_err_coeff: 1.0
m_l1: 0.5
prioritize_dyn: true
q_l1: -0.2
speed_factor_for_curvature: 1.0
speed_factor_for_lat_err: 1.0
speed_lookahead: 0.25
speed_lookahead_for_steer: 0.0
start_scale_speed: 5.5
steer_gain_for_speed: 1.0
t_clip_max: 5.0
t_clip_min: 1.25
trailing_d_gain: 0.2
trailing_gap: 1.5
trailing_i_gain: 0.0
trailing_p_gain: 1.5
velocity_step: 0.5
speed_diff_thres: 0.5
start_speed: 6.0
start_curvature_factor: 1.5
dyn_model_exp: 1.2
v_max: 8.0
b_ax_max_machines: 3.0
a_y_max: 5.0
a_x_max: 5.0