
# erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset 
#4614
# eprm = rpm(motor) x poles x 0.5
# Traxxas Velineon 3551R 3500kv 4poles
# Hobbywing XeRun Axe550r2 4poles
# speed_to_erpm_gain: 3801.79
# speed_to_erpm_offset: 445.0

# speed_to_erpm_gain: 3017.79 # 2700.79
# speed_to_erpm_gain: 3050.79 # 2700.79
speed_to_erpm_gain: 3041.95 # 2700.79
speed_to_erpm_offset: 0.0

tachometer_ticks_to_meters_gain: 0.00225

# servo smoother - limits rotation speed and smooths anything above limit
# max_servo_speed: 3.2 # radians/second
max_servo_speed: 13.089 # radians/second
servo_smoother_rate: 75.0 # messages/sec
servo_timeout: 0.1 # (stop publishing after inactive for) s

# motor rpm smoother - limits acceleration and smooths anything above limit
# not used when sending current commands
max_acceleration: 3.5 # meters/second^2
max_acceleration_start_ratio: 0.3
max_speed_start: 1.0 # meters/second^2


throttle_smoother_rate: 75.0 # messages/sec
motor_timeout: 0.1 # (stop publishing after inactive for) s

# motor current smoother - limits current and filters with time constant
max_accel_current: 65 #A
max_brake_current: 50 #A ()
current_time_constant: 0.05 #s 
current_smoother_rate: 100.0 # messages/sec
current_timeout: 0.1 # s for correct interpolation the controller must publish at frequency higher than 1/this

# servo value (0 to 1) =  steering_angle_to_servo_gain * steering angle (radians) + steering_angle_to_servo_offset
#-1.2135


# steering_angle_to_servo_gain: -0.945 # obtained 03.02.2023
# steering_angle_to_servo_offset: 0.555 # obtained 03.02.2023

# steering_angle_to_servo_gain: 0.885 # obtained 03.02.2023
steering_angle_to_servo_gain: 0.5153 # obtained 03.02.2023
steering_angle_to_servo_offset: 0.505 # 0.515 # for car2 0.538

# steering_angle_to_servo_offset: 0.445 # obtained 19.02.2023

#offset johnny 0.417
#0.5304

# current (A, 0 - 100) = gain * acceleration (m/s2) + gain * velocity
acceleration_to_current_gain: 10.0 #8.938
deceleration_to_current_gain: 25.0 #5.936
velocity_to_current_gain: 3.693

# publish odom to base link tf
vesc_to_odom/publish_tf: false

# car wheelbase is about 25cm 
wheelbase: 0.33

vesc_driver:
  port: /dev/VESC
  duty_cycle_min: 0.0
  duty_cycle_max: 0.0
  current_min: 0.0
  current_max: 100.0
  brake_min: -20000.0
  brake_max: 200000.0
  speed_min: -69000
  speed_max: 69000
  position_min: 0.0
  position_max: 0.0
  servo_min: 0.0
  servo_max: 1.0

# Simple Mux Paramater
joy_max_speed: 6.0
joy_max_steer: 0.6
joy_freshness_threshold: 1.0
